config/routes.rb
RailsBlog::Application.routes.draw do
  devise_for :users

  match 'tags/:tag' => 'blog_posts#index', :as => :tag

  resources :blog_posts do
    resources :user_comments
  end

  root :to => 'blog_posts#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :blog_post
  
  attr_accessible :usrfile
  has_attached_file :usrfile, :styles => lambda{ |a| ["image/jpeg", "image/png"].include?( a.content_type ) ? { :thumb => "100x100>" } : {}  }

  validates_attachment :usrfile, :size => { :in => 0..2.megabytes }

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tag_list, :assets_attributes

  validates :title, :presence => true, :length => { :minimum => 5 }
  validates :content, :presence => true, :length => { :minimum => 10 }

  belongs_to :user
  has_many :user_comments, :dependent => :destroy
  has_many :assets, :dependent => :destroy

  accepts_nested_attributes_for :assets, :allow_destroy => true

  acts_as_taggable_on :tags

  def next
  	BlogPost.where("id > ?", id).first
  end

  def prev
  	BlogPost.where("id < ?", id).last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts, :dependent => :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  validates :username, :presence => true, :length => { :minimum => 5 }, :uniqueness => true
end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  belongs_to :blog_post
  
  attr_accessible :body, :commenter
  
  validates :commenter, :presence => true
  validates :body, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :get_blog_post, only: [:edit, :update, :destroy]
  before_filter :check_authorisation, only: [:edit, :update, :destroy]

  def get_blog_post
    @blog_post = BlogPost.find(params[:id]) 
  end

  def check_authorisation
    unless @blog_post.user_id == current_user.id
      redirect_to blog_posts_path, notice: 'You are not authorized to modify that resource'
    end
  end

  # GET /blog_posts
  # GET /blog_posts.json
  def index

    order_string = "created_at DESC"
    @attribute = ""

    @link_filter = params[:link_filter]

    puts 'params', params, "\n\n"

    @content_filter = nil
    @user_filter = nil
    
    if params[:gsearch] && params[:gsearch].length > 0
        @content_filter = params[:gsearch]
    end

    #users = User.where('username LIKE ?', '%nitbhjbish%')
    #users

    if params[:filter]
        order_string = "#{params[:filter]} #{params[:direction]}"
        @attribute = params[:filter]  
    end
    
    #puts 'attribute', @attribute

    pagination_params = {:page => params[:page], :per_page => 5, :order => order_string}
    
    if @content_filter
        @blog_posts = BlogPost.where('title LIKE ? OR content LIKE ?', "%#{@content_filter}%", "%#{@content_filter}%").paginate(pagination_params)
    else
      if params[:tag]
        @blog_posts = BlogPost.tagged_with(params[:tag]).paginate(pagination_params)
      else
        @blog_posts = BlogPost.paginate(pagination_params)
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_posts }
      format.js
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])
    @next = @blog_post.next
    @prev = @blog_post.prev

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_post }
      format.js
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(params[:blog_post])
    @blog_post.user_id = current_user.id

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render json: @blog_post, status: :created, location: @blog_post }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
    before_filter :get_blog_post
    before_filter :check_authorisation, only: :destroy

    def get_blog_post
        @blog_post = BlogPost.find(params[:blog_post_id])
    end

    def check_authorisation
        unless @blog_post.user_id == current_user.id
          redirect_to blog_post_path(@blog_post), notice: 'You can only delete comments on your own blog'
        end
    end

    def create
        @user_comment = @blog_post.user_comments.create(params[:user_comment])
        respond_to do |format|
            format.html { redirect_to blog_post_path(@blog_post) }
            format.js
        end   
    end

    def destroy
        @user_comment = @blog_post.user_comments.find(params[:id])
        @user_comment.destroy
        @del_id = params[:id]
        respond_to do |format|
            format.html { redirect_to blog_post_path(@blog_post) }
            format.js
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  
  def get_username(user_id)
    usr = User.find(user_id)
    if usr
        return usr.username
    else
        return "unknown"
    end
  end

  def is_authorized?(user_id)
    user_id == current_user.id
  end

  def format_tags(tags_list)
    "<strong>" + tags_list.map { |tag| link_to tag, tag_path(:tag => tag) } .join('</strong>, <strong>') + "</strong>"
  end

  def get_link(asset)
      ret = "<div class=\"field\">"
      if asset.object.usrfile_content_type.include? 'image'
          ret += link_to(image_tag(asset.object.usrfile.url(:thumb)), asset.object.usrfile.url)
      else
          ret += link_to(asset.object.usrfile_file_name , asset.object.usrfile.url)
      end
      ret += asset.check_box :_destroy
      ret += asset.label :_destroy, 'Remove'
      ret += "</div>"
  end

  def get_attachments(assets)
      ret = ""
      for asset in assets
        ret += "<div class=\"attachment\">"
        if asset.usrfile_content_type.include? 'image'
            ret += link_to(image_tag(asset.usrfile.url(:thumb)), asset.usrfile.url)
        else
            ret += link_to(asset.usrfile_file_name , asset.usrfile.url)
        end
        ret += "</div>"
      end
      ret
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div class="blog-post">
  <div class="post-header">
    <h2><%= link_to blog_post.title, blog_post %></h2>
    
    <div class="pull-left">
      Author:<strong id="author"><%= get_username(blog_post.user_id) %></strong> 
    </div>
    <div class="pull-right">
      <% if user_signed_in? and is_authorized?(blog_post.user_id) %>
        <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
        <%= link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
  
  <hr />
  
  <div class="post-content"> <%= blog_post.content %> </div>
  <div id="timestamps">
    <span id="created_dt">created:<%= blog_post.created_at %></span> updated:<span id="updated_dt"><%= blog_post.updated_at %></span>
  </div> 
  <div class="post-tags">
    tags: <%= raw format_tags(blog_post.tag_list) %>
  </div>
</div>

app/views/blog_posts/_form.html.erb
<% 2.times { @blog_post.assets.build } %>
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 35, :maxlength => 100 %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="attachments">
    <%= f.fields_for :assets do |asset| %>
      <% if asset.object.new_record? %>
        <div class="field">
          <%= asset.file_field :usrfile %>
        </div>
      <% else %>
        <%= raw get_link asset %>
      <% end %>
    <% end %>
  </div>


  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list , :size => 35, :maxlength => 50 %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class => "pull-left" %>
    <%= button_to "Back", :back %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<%= render 'form' %>

app/views/blog_posts/index.html.erb
<div id="filters" class="pull-left">
  

  <%= form_tag blog_posts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :gsearch, params[:gsearch] %>
    <%= submit_tag "Search", :name => nil, :id => 'search_submit' %>
  </p>
  <% end %>

  

</div>
<div id="sorts" class="pull-right">
	
	Created<%= link_to "^", root_path(:filter => "created_at", :direction => "ASC", :link_filter => "1" ), :id => "created", remote: true  %>

	Updated<%= link_to "^", root_path(:filter => "updated_at", :direction => "ASC", :link_filter => "1"), :id => "updated", remote: true  %>

</div>
<div class="clearfix"></div>

<div id="blog-posts">
  <%= render @blog_posts %>
</div>

<div class="digg_pagination">
  <%= will_paginate @blog_posts %>
</div>

app/views/blog_posts/index.js.erb
<% if @link_filter %>
	$('#blog-posts').empty();
<% end %>



<% if @link_filter && @attribute == "created_at" %>
	console.log('created');
	
	if($('#created').text() === '^') {
        $('#created').text('v');
        var ahref = $('#created').attr('href');
        $('#created').attr('href', ahref.replace('ASC', 'DESC'));
    } else {
        $('#created').text('^');
        var ahref = $('#created').attr('href');
        $('#created').attr('href', ahref.replace('DESC', 'ASC'));
    }

<% end %>

<% if @link_filter && @attribute == "updated_at" %>
	console.log('updated');
	
	if($('#updated').text() === '^') {
        $('#updated').text('v');
        var ahref = $('#updated').attr('href');
        $('#updated').attr('href', ahref.replace('ASC', 'DESC'));
    } else {
        $('#updated').text('^');
        var ahref = $('#updated').attr('href');
        $('#updated').attr('href', ahref.replace('DESC', 'ASC'));
    }

<% end %>




$('#blog-posts').append('<%= j render(@blog_posts) %>');

<% if @blog_posts.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @blog_posts %>');

<% end %>

app/views/blog_posts/new.html.erb
<%= render 'form' %>

app/views/blog_posts/show.html.erb
<div id="navigate">
    <div id="prev" class="pull-left"><%= link_to "< Prev", @prev, remote: true %></div>
    <div id="next" class="pull-right"><%= link_to "Next >", @next, remote: true %></div>
    <div class="clearfix"></div>
</div>
<div class="blog-post">
    <div class="post-header"> 
        <h2><%= @blog_post.title %></h2>
        
        <div class="pull-left">
            Author:<strong id="author"><%= get_username(@blog_post.user_id) %></strong> 
        </div>
        <div id="modification" class="pull-right">
            <% if user_signed_in? and is_authorized?(@blog_post.user_id) %>
                <%= link_to 'Edit', edit_blog_post_path(@blog_post) %><%= link_to 'Delete', @blog_post, method: :delete, 
                data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
        <div class="clearfix"></div>
    </div>

    <hr />
    
    <div class="post-content"> <%= @blog_post.content %> </div>
</div>
<br />

<% unless @blog_post.assets.empty? %>
    <div class="post-attachments">
        <h3>Attachments:</h3>
        <%= raw get_attachments(@blog_post.assets) %>
    </div>
<% end %> 

<h3>tags:</h3>
<div class="post-tags">
    <%= raw format_tags(@blog_post.tag_list) %>
</div>

<div class="post-comments">
    <% unless @blog_post.user_comments.empty? %>
        <h3>Comments:</h3>
        <div class="comments">
            <%= render @blog_post.user_comments %>
        </div>
    <% end %>
    <div class="new-comment">
        <%= render 'user_comments/comment_form' %>    
    </div>
</div>

app/views/blog_posts/show.js.erb
$('.post-header h2').text('<%= @blog_post.title %>');
$('#author').text('<%= get_username(@blog_post.user_id) %>');
$('.post-content').text('<%= @blog_post.content %>');
$('#prev').html('<%= link_to "< Prev", @prev, remote: true %>');
$('#next').html('<%= link_to "Next >", @next, remote: true %>');
$('.post-tags').html('<%= raw format_tags(@blog_post.tag_list) %>');
$('.post-comments h3').remove();
$('.post-comments .comments').remove();

$('#modification').empty();
<% if user_signed_in? and is_authorized?(@blog_post.user_id) %>
	$('<%= link_to "Edit", edit_blog_post_path(@blog_post) %>').appendTo('#modification');
	$('<%= link_to "Delete", @blog_post, method: :delete, data: { confirm: "Are you sure?" } %>').appendTo('#modification');
		
<% end %>

<% unless @blog_post.user_comments.empty? %>
	$('.post-comments').prepend('<div class="comments"></div>');
	$('.post-comments').prepend('<h3>Comments:</h3>');
	$('<%= j render @blog_post.user_comments %>').appendTo('.post-comments .comments');
<% end %>
$('.new-comment').html('<%= j render "user_comments/comment_form" %>');

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Blog Posts", blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoR Blog Application</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <h1 id="loadmsg">Loading...</h1>
    <div class="pull-left">
      <%= link_to "Home", blog_posts_path %> |
      <%= link_to 'New Blog post', new_blog_post_path %>
    </div>
    <div class="pull-right">
        <% if user_signed_in? %>
            <strong><%= current_user.username %></strong> | 
            <%= link_to "Settings", edit_user_registration_path %> |
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %> |
            <%= link_to "Sign In", new_user_session_path %>
        <% end %>
    </div>
    <div class="clearfix"></div>
    <br />
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>

    <%= yield %>



    <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/user_comments/_comment_form.html.erb
<%= form_for([@blog_post, @blog_post.user_comments.build], remote: true) do |f| %>
  <div class="field">
    <%= f.label :commenter, "Name" %><br />
    <%= f.text_field :commenter, :maxlength => 15 %>
  </div>
  <div class="field">
    <%= f.label :body, "Comment" %><br />
    <%= f.text_area :body, :rows => 2 %>
  </div>
  <div class="actions">
    <%= f.submit "Add comment"%>
  </div>
  
<% end %>

app/views/user_comments/_user_comment.html.erb
<p id="delete_comment_<%= user_comment.id %>"> 
    <b><%= user_comment.commenter %></b>, <%= user_comment.body %> 
    <% if user_signed_in? %>
      <%= link_to '<delete>', [user_comment.blog_post, user_comment],
                   :confirm => 'Are you sure?',
                   :method => :delete, :remote => true %>
    <% end %>
</p>

app/views/user_comments/create.js.erb
if($('.comments').length === 0) {
	$('.post-tags').after('<div class="post-comments"></div>');
}
$('.comments').append('<%= j render @user_comment %>');
$('#user_comment_commenter').val("");
$('#user_comment_body').val("");

app/views/user_comments/destroy.js.erb
$('#delete_comment_<%= @del_id %>').remove();